const REQUIRED_VALIDATION_MESSAGE = 'The field is required!';
const USERNAME_VALIDATION_MESSAGE = 'The username must be at least 6 characters long.';
const EMAIL_VALIDATION_MESSAGE = 'Please enter a valid e-mail address!';
const PASSWORD_VALIDATION_MESSAGE = 'Must be at least 6 characters';

module.exports = {
  REQUIRED_VALIDATION_MESSAGE: REQUIRED_VALIDATION_MESSAGE,
  USERNAME_VALIDATION_MESSAGE: USERNAME_VALIDATION_MESSAGE,
  EMAIL_VALIDATION_MESSAGE: EMAIL_VALIDATION_MESSAGE,
  PASSWORD_VALIDATION_MESSAGE: PASSWORD_VALIDATION_MESSAGE
}